DATA = 'data'
INCLUDED = 'included'
FULL_NAME = 'fullName'
FIRST_NAME = 'firstName'
LAST_NAME = 'lastName'
SUMMARY = 'summary'
PROFILE_KEY = '*profile'

MAX_PAGE = 10
SEARCH_URL = 'https://www.linkedin.com/search/results/people/?facetConnectionOf=%5B%22{user_key}%22%5D&facetNetwork=%5B%22F%22%2C%22S%22%5D&origin=MEMBER_PROFILE_CANNED_SEARCH&{page}'
ELEMENTS = 'elements'
MEMBER_DISTANCE = 'memberDistance'
MEMBER_DISTANCE_VALUE = 'value'
PUBLIC_IDENTIFIER = 'publicIdentifier'
TITLE = 'title'
TITLE_USER_FULL_NAME = 'text'
